# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://tiliatranslations.it
title: Tilia Translations di Angela Brisotto
email: angela@tiliatranslations.it
author: Angela Brisotto
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2021 Tilia Translations di Angela Brisotto. All Rights Reserved.
TILIA TRANSLATIONS DI ANGELA BRISOTTO
Via Daniele Manin, n. 4/10
31027 Spresiano (TV)
Partita IVA: 05247030264
Professionista di cui alla Legge n. 4 del 14.1.2013
'
credits: 'Credits: Landing Page is a theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: linkedin
    url: https://www.linkedin.com/in/angela-brisotto
  - title: email
    url: mailto:angela@tiliatranslations.it
