# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://tiliatranslations.it
title: Tilia Translations di Angela Brisotto
email: angela@tiliatranslations.it
author: Angela Brisotto
description: English to Italian and Polish to Italian translator specializing in culture, arts, and crafts, sustainability, and language learning.|Tłumaczka z polskiego na włoski i z angielskiego na włoski specjalizująca się w kulturze, sztuce i rzemiośle, ekologii, i nauce języka.|Traduttrice dall’inglese all’italiano e dal polacco all’italiano specializzata in cultura, arte e artigianato, sostenibilità e apprendimento delle lingue.

copyright: 'Copyright &copy; 2021 Tilia Translations di Angela Brisotto. All Rights Reserved.
<br>
<br>
TILIA TRANSLATIONS DI ANGELA BRISOTTO
<br>
Via Daniele Manin, n. 4/10
<br>
31027 Spresiano (TV)
<br>
Partita IVA: 05247030264
<br>
Professionista di cui alla Legge n. 4 del 14.1.2013
<br>
angela@tiliatranslations.it
'
credits: 'Credits: Theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: linkedin
    url: https://www.linkedin.com/in/angela-brisotto
  - title: mailto
    url: mailto:angela@tiliatranslations.it
